//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professeur
    {
        public Professeur()
        {
            this.Sujet = new HashSet<Sujet>();
            this.Horaire = new HashSet<ProfesseurHoraire>();
        }
    
        public int Id { get; set; }
        public int Aciennete { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Coordonnees Coordonnees { get; set; }
        public virtual ICollection<Sujet> Sujet { get; set; }
        public virtual ICollection<ProfesseurHoraire> Horaire { get; set; }
    }
}
