//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Etudiant> EtudiantSet { get; set; }
        public virtual DbSet<Login> LoginSet { get; set; }
        public virtual DbSet<Paiement> PaiementSet { get; set; }
        public virtual DbSet<Inscription> InscriptionSet { get; set; }
        public virtual DbSet<Professeur> ProfesseurSet { get; set; }
        public virtual DbSet<Sujet> SujetSet { get; set; }
        public virtual DbSet<Cours> CoursSet { get; set; }
        public virtual DbSet<Coordonnees> CoordonneesSet { get; set; }
        public virtual DbSet<ProfesseurHoraire> ProfesseurHoraireSet { get; set; }
        public virtual DbSet<CoursHoraire> CoursHoraireSet { get; set; }
        public virtual DbSet<Heure> HeureSet { get; set; }
        public virtual DbSet<Jour> JourSet { get; set; }
    }
}
