//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityContainer : DbContext
    {
        public EntityContainer()
            : base("name=EntityContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Etudiant> EtudiantSet { get; set; }
        public DbSet<Login> LoginSet { get; set; }
        public DbSet<Paiement> PaiementSet { get; set; }
        public DbSet<Inscription> InscriptionSet { get; set; }
        public DbSet<Professeur> ProfesseurSet { get; set; }
        public DbSet<Sujet> SujetSet { get; set; }
        public DbSet<Cours> CoursSet { get; set; }
        public DbSet<Coordonnees> CoordonneesSet { get; set; }
        public DbSet<ProfesseurHoraire> ProfesseurHoraireSet { get; set; }
        public DbSet<CoursHoraire> CoursHoraireSet { get; set; }
        public DbSet<Heure> HeureSet { get; set; }
        public DbSet<Jour> JourSet { get; set; }
    }
}
