//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscription
    {
        public Inscription()
        {
            this.Paiement = new HashSet<Paiement>();
        }
    
        public int Id { get; set; }
        public bool Annule { get; set; }
    
        public virtual Sujet Etudiant { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual ICollection<Paiement> Paiement { get; set; }
    }
}
